#!/bin/sh
# regen.sh — regenerate this exercise's fixtures from the Rust reference.
#
# Maintenance helper only; no BUILD rule depends on it. Run it after changing
# the curated case list (oracle/src/rush00.rs, const FIXED) or edge_cases.tsv:
#
#     sh c-piscine-rush-00/tests/ex00/regen.sh
#
# It rewrites, in this directory:
#   cases.tsv            the curated "<label> <x> <y>" list test_rush.c replays
#   expected_rush0N.txt  the "<label> <escaped rectangle>" table it is diffed against
#   expected_robust.txt  "<label> survived" for every degenerate case
#   expected_putchar.txt the exact bytes test_putchar.c must produce
#
# cases.tsv and expected_rush0N.txt are cut from the SAME oracle stream
# (`oracle rush_vN_fixed`), which is what makes it impossible for the labels the
# harness prints and the labels the fixture expects to drift apart.
#
# The oracle is built with Bazel if available, else cargo.
set -eu

HERE=$(CDPATH='' cd -- "$(dirname "$0")" && pwd)
ROOT=$(CDPATH='' cd -- "$HERE/../../.." && pwd)

if command -v bazel >/dev/null 2>&1 && bazel build //oracle:oracle >/dev/null 2>&1; then
	ORACLE="$ROOT/bazel-bin/oracle/oracle"
else
	echo "regen.sh: bazel unavailable — falling back to cargo" >&2
	( cd "$ROOT/oracle" && cargo build --release >/dev/null )
	ORACLE="$ROOT/oracle/target/release/oracle"
fi
[ -x "$ORACLE" ] || { echo "regen.sh: no oracle binary at $ORACLE" >&2; exit 1; }

"$ORACLE" check >/dev/null || { echo "regen.sh: oracle self-check FAILED — refusing to regenerate" >&2; exit 1; }

# 1. the curated list + its five expected tables, from one stream per variant
"$ORACLE" rush_v0_fixed 0 0 | cut -f1,2,3 > "$HERE/cases.tsv.new"
for n in 0 1 2 3 4; do
	"$ORACLE" "rush_v${n}_fixed" 0 0 | cut -f1,4 > "$HERE/expected_rush0${n}.txt"
	# every variant must agree on the case list itself
	"$ORACLE" "rush_v${n}_fixed" 0 0 | cut -f1,2,3 > "$HERE/cases.tsv.check"
	cmp -s "$HERE/cases.tsv.new" "$HERE/cases.tsv.check" ||
		{ echo "regen.sh: variant $n disagrees about the case list" >&2; exit 1; }
	rm -f "$HERE/cases.tsv.check"
done
{
	echo "# Curated case list for tests/ex00/test_rush.c — GENERATED by regen.sh."
	echo "# Source of truth: oracle/src/rush00.rs, const FIXED. Do not hand-edit."
	echo "# Format: <label><TAB><x><TAB><y>"
	cat "$HERE/cases.tsv.new"
} > "$HERE/cases.tsv"
rm -f "$HERE/cases.tsv.new"

# 2. the robustness table: every degenerate case must merely survive
{
	grep -v '^[[:space:]]*#' "$HERE/edge_cases.tsv" | grep -v '^[[:space:]]*$' |
		awk -F'\t' '{ printf "%s\tsurvived\n", $1 }'
	printf '3x3 unchanged by the degenerate calls\tYES\n'
} > "$HERE/expected_robust.txt"

# 3. ft_putchar's exact bytes (see test_putchar.c for the case order)
printf 'OK\n42 -|/\\~\t\000\177\200\377\n' > "$HERE/expected_putchar.txt"

echo "regen.sh: fixtures rewritten in $HERE"
