# **************************************************************************** #
#                                                                              #
#    Makefile (stub)  --  ft_tail
#    TODO: implement all / clean / fclean / re so that "make" builds ft_tail
#                                                                              #
# **************************************************************************** #

NAME = ft_tail
SRC = ft_tail.c

all:
	@echo "TODO: build $(NAME) from $(SRC)"

clean:
	@echo "TODO: clean object files"

fclean: clean
	@echo "TODO: remove $(NAME)"

re: fclean all

.PHONY: all clean fclean re
