# **************************************************************************** #
#                                                                              #
#   Makefile (stub) -- a toy program whose Makefile is not written yet         #
#                                                                              #
#   The recipe only echoes and names no source, so `make -Bn` names none.      #
#                                                                              #
# **************************************************************************** #

NAME = toy27

$(NAME):
	@echo "TODO: build $(NAME)"

.PHONY:
