# **************************************************************************** #
#                                                                              #
#   Makefile (stub) -- a toy Makefile turned in alone                          #
#                                                                              #
#   The grader brings srcs/toy.c itself (the contract's `provided`), so the    #
#   copy of it beside this file is one the subject never asked for.            #
#                                                                              #
# **************************************************************************** #

NAME = libtoy.a

$(NAME):
	@echo "TODO: build $(NAME) from srcs/"

.PHONY:
