# **************************************************************************** #
#                                                                              #
#   Makefile (stub) -- a toy program                                           #
#                                                                              #
#   What an exercise nobody has started ships: a default goal whose recipe     #
#   only echoes, so `make -Bn` names no source and nothing is built.           #
#                                                                              #
# **************************************************************************** #

NAME = toy
SRC  =

$(NAME):
	@echo "TODO: build $(NAME) from $(SRC)"

.PHONY:
