NAME = ft_display_file
SRC = ft_display_file.c

all: $(NAME)

$(NAME):
	@echo "TODO: build $(NAME) from $(SRC)"

clean:
	@echo "TODO: clean object files"

fclean: clean
	@echo "TODO: remove $(NAME)"

.PHONY: all clean fclean
