# **************************************************************************** #
#                                                                              #
#   Makefile (stub) -- a toy program with a source it never builds             #
#                                                                              #
#   The recipe only echoes: `make -Bn` reads the compile line it prints, which #
#   names toy19.c and not toy19_unused.c, and nothing runs.                    #
#                                                                              #
# **************************************************************************** #

NAME = toy19

$(NAME):
	@echo cc -Wall -Wextra -Werror -o $(NAME) toy19.c

.PHONY:
