# Makefile - build libft.a from srcs/ using includes/ft.h.
#
# TODO: define NAME = libft.a, SRCS in srcs/, CC = cc, CFLAGS = -Wall -Wextra
# TODO: -Werror -Iincludes, and the rules: all, $(NAME), clean, fclean, re.
# Not implemented yet.
