# **************************************************************************** #
#                                                                              #
#    Makefile (stub)  --  ft_cat
#    TODO: implement all / clean / fclean / re so that "make" builds ft_cat
#                                                                              #
# **************************************************************************** #

NAME = ft_cat
SRC = ft_cat.c

all:
	@echo "TODO: build $(NAME) from $(SRC)"

clean:
	@echo "TODO: clean object files"

fclean: clean
	@echo "TODO: remove $(NAME)"

re: fclean all

.PHONY: all clean fclean re
