# **************************************************************************** #
#                                                                              #
#   Makefile (stub) -- a toy program run through an argument table             #
#                                                                              #
#   The recipe only echoes: `make -Bn` reads the compile line it prints,       #
#   which names toy24.c, and nothing runs.                                     #
#                                                                              #
# **************************************************************************** #

NAME = toy24

$(NAME):
	@echo cc -Wall -Wextra -Werror -o $(NAME) toy24.c

.PHONY:
