NAME = libft.a

all: $(NAME)

$(NAME):
	@echo "TODO: build $(NAME) from srcs/ with the headers in includes/"

clean:
	@echo "TODO: clean object files"

fclean: clean
	@echo "TODO: remove $(NAME)"

re: fclean all

.PHONY: all clean fclean re
