# **************************************************************************** #
#                                                                              #
#   Makefile (stub) -- a toy program turned in at the repository root          #
#                                                                              #
#   Its sources are in srcs/ and its header in includes/, the layout of a      #
#   Common Core project. The recipe only echoes: `make -Bn` reads the compile  #
#   line it prints -- which files, and which -I directory -- and nothing runs. #
#                                                                              #
# **************************************************************************** #

NAME = toy_root

$(NAME):
	@echo cc -Wall -Wextra -Werror -I includes -o $(NAME) srcs/main.c

.PHONY:
