# **************************************************************************** #
#                                                                              #
#   Makefile (stub) -- a toy program whose Makefile is written                 #
#                                                                              #
#   The recipe only echoes: `make -Bn` reads the compile line it prints, which #
#   names toy28.c and -I includes, not toy28_unused.c, and nothing runs.       #
#                                                                              #
# **************************************************************************** #

NAME = toy28

$(NAME):
	@echo cc -Wall -Wextra -Werror -I includes -o $(NAME) toy28.c

.PHONY:
