# **************************************************************************** #
#                                                                              #
#   Makefile (stub) -- rush-02                                                 #
#                                                                              #
#   The subject names three rules and no others: $(NAME), clean and fclean.    #
#   It compiles the project with:   make fclean   then   make                  #
#   $(NAME) is first on purpose, so a bare `make` reaches it.                  #
#                                                                              #
#   SRC is left empty deliberately. "Files to turn in: Makefile and all the    #
#   necessary files" and "you are free to organize your files as you wish",    #
#   so how the team splits the sources is theirs to decide, not this stub's.   #
#                                                                              #
# **************************************************************************** #

NAME = rush-02
SRC  =

$(NAME):
	@echo "TODO: build $(NAME) from $(SRC)"

clean:
	@echo "TODO: remove the temporary files the build produced"

fclean: clean
	@echo "TODO: also remove $(NAME)"

.PHONY: clean fclean
