# Makefile - build the do-op program.
#
# The subject does not list this file under "Files to turn in" ("Your program
# files"), but p.11 shows the Moulinette's own session starting with:
#
#     $> make clean
#     $> make
#     $> ./do-op
#
# so a build that does not answer `make clean` and `make` is a zero on the
# transcript the subject prints, whatever the program does.
#
# TODO: define NAME = do-op, the sources, CC = cc, CFLAGS = -Wall -Wextra
# TODO: -Werror, and the rules: all, $(NAME), clean.
# Not implemented yet.
